# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto"N\n\x0eSessionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\x12\n\nreturn_url\x18\x03 \x01(\t":\n\x0fSessionResponse\x12\x13\n\x0b\x65xpire_date\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t"2\n\x0f\x43ustomerRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t")\n\x10\x43ustomerResponse\x12\x15\n\rcustomer_uuid\x18\x01 \x01(\t">\n\x12\x41uthCompanyRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t"(\n\x13\x41uthCompanyResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t"L\n\x11IntrospectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t"H\n\x12IntrospectResponse\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0f\n\x07revoked\x18\x02 \x01(\x08\x12\x12\n\nchecked_at\x18\x03 \x01(\x03\x32\xfc\x01\n\tAuthProto\x12\x34\n\rCreateSession\x12\x0f.SessionRequest\x1a\x10.SessionResponse"\x00\x12\x37\n\x0e\x43reateCustomer\x12\x10.CustomerRequest\x1a\x11.CustomerResponse"\x00\x12\x42\n\x13\x41uthenticateCompany\x12\x13.AuthCompanyRequest\x1a\x14.AuthCompanyResponse"\x00\x12<\n\x0fIntrospectToken\x12\x12.IntrospectRequest\x1a\x13.IntrospectResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "auth_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SESSIONREQUEST"]._serialized_start = 14
    _globals["_SESSIONREQUEST"]._serialized_end = 92
    _globals["_SESSIONRESPONSE"]._serialized_start = 94
    _globals["_SESSIONRESPONSE"]._serialized_end = 152
    _globals["_CUSTOMERREQUEST"]._serialized_start = 154
    _globals["_CUSTOMERREQUEST"]._serialized_end = 204
    _globals["_CUSTOMERRESPONSE"]._serialized_start = 206
    _globals["_CUSTOMERRESPONSE"]._serialized_end = 247
    _globals["_AUTHCOMPANYREQUEST"]._serialized_start = 249
    _globals["_AUTHCOMPANYREQUEST"]._serialized_end = 311
    _globals["_AUTHCOMPANYRESPONSE"]._serialized_start = 313
    _globals["_AUTHCOMPANYRESPONSE"]._serialized_end = 353
    _globals["_INTROSPECTREQUEST"]._serialized_start = 355
    _globals["_INTROSPECTREQUEST"]._serialized_end = 431
    _globals["_INTROSPECTRESPONSE"]._serialized_start = 433
    _globals["_INTROSPECTRESPONSE"]._serialized_end = 505
    _globals["_AUTHPROTO"]._serialized_start = 508
    _globals["_AUTHPROTO"]._serialized_end = 760
# @@protoc_insertion_point(module_scope)
