# Generated by Django 4.2.10 on 2024-05-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения/оплаты')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('text', models.TextField(max_length=200, verbose_name='Текст сообщения')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='Параметры выборки')),
                ('status', models.CharField(choices=[('launched', 'запущена'), ('scheduled', 'запланирована'), ('canceled', 'отменена'), ('finished', 'завершена')], default='scheduled', max_length=15, verbose_name='Статус рассылки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Номер телефона')),
                ('carrier', models.CharField(choices=[('mts', 'мтс'), ('megafon', 'мегафон'), ('beeline', 'билайн'), ('tele2', 'теле2'), ('yota', 'йота')], max_length=10, verbose_name='Код оператора')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тег')),
                ('tz_name', models.CharField(max_length=20, verbose_name='Часовой пояс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('ok', 'доставлено'), ('failed', 'не доставлено'), ('processing', 'в обработке'), ('canceled', 'отменено')], default='processing', max_length=15, verbose_name='Статус отправки')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='service.campaign', verbose_name='Рассылка')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='service.customer', verbose_name='Клиент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
